// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOBvmi9-4VRfF-aGlMoNM_MqAQBGLjAvA',
    appId: '1:179699417895:web:0bbde8bb85ba4fac8c9f02',
    messagingSenderId: '179699417895',
    projectId: 'control-ganadero-41214',
    authDomain: 'control-ganadero-41214.firebaseapp.com',
    storageBucket: 'control-ganadero-41214.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJrVNsjs1ln5uNZ8EZFUUOo_WP09V2qw',
    appId: '1:179699417895:android:55a0b876c6e6e5298c9f02',
    messagingSenderId: '179699417895',
    projectId: 'control-ganadero-41214',
    storageBucket: 'control-ganadero-41214.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM1wmPsCy9_np8-jbOFPoskVLVlyHYigQ',
    appId: '1:179699417895:ios:69280e329f81b3738c9f02',
    messagingSenderId: '179699417895',
    projectId: 'control-ganadero-41214',
    storageBucket: 'control-ganadero-41214.firebasestorage.app',
    iosBundleId: 'com.example.controlGanadero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM1wmPsCy9_np8-jbOFPoskVLVlyHYigQ',
    appId: '1:179699417895:ios:69280e329f81b3738c9f02',
    messagingSenderId: '179699417895',
    projectId: 'control-ganadero-41214',
    storageBucket: 'control-ganadero-41214.firebasestorage.app',
    iosBundleId: 'com.example.controlGanadero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOBvmi9-4VRfF-aGlMoNM_MqAQBGLjAvA',
    appId: '1:179699417895:web:96af8cfe6ce1b3758c9f02',
    messagingSenderId: '179699417895',
    projectId: 'control-ganadero-41214',
    authDomain: 'control-ganadero-41214.firebaseapp.com',
    storageBucket: 'control-ganadero-41214.firebasestorage.app',
  );
}
